mod client;
mod pool;

pub use client::BackendClient;
pub use pool::BackendClientPool;

// Include generated protobuf code or use stub if not available
#[allow(unused)]
pub mod pb {
    // This will be generated by tonic-build if protoc is available
    // Otherwise we get compile errors, which is expected for PoC
    #[cfg(not(skip_proto_gen))]
    tonic::include_proto!("doris");
}
