// Autogenerated by Thrift Compiler (0.19.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_extern_crates)]
#![allow(clippy::too_many_arguments, clippy::type_complexity, clippy::vec_box, clippy::wrong_self_convention)]
#![cfg_attr(rustfmt, rustfmt_skip)]

use std::cell::RefCell;
use std::collections::{BTreeMap, BTreeSet};
use std::convert::{From, TryFrom};
use std::default::Default;
use std::error::Error;
use std::fmt;
use std::fmt::{Display, Formatter};
use std::rc::Rc;

use thrift::OrderedFloat;
use thrift::{ApplicationError, ApplicationErrorKind, ProtocolError, ProtocolErrorKind, TThriftClient};
use thrift::protocol::{TFieldIdentifier, TListIdentifier, TMapIdentifier, TMessageIdentifier, TMessageType, TInputProtocol, TOutputProtocol, TSerializable, TSetIdentifier, TStructIdentifier, TType};
use thrift::protocol::field_id;
use thrift::protocol::verify_expected_message_type;
use thrift::protocol::verify_expected_sequence_number;
use thrift::protocol::verify_expected_service_call;
use thrift::protocol::verify_required_field_exists;
use thrift::server::TProcessor;

use crate::data_sinks;
use crate::exprs;
use crate::partitions;
use crate::plan_nodes;
use crate::query_cache;
use crate::types;

//
// TPlanFragment
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct TPlanFragment {
  pub plan: Option<plan_nodes::TPlan>,
  pub output_exprs: Option<Vec<exprs::TExpr>>,
  pub output_sink: Option<data_sinks::TDataSink>,
  pub partition: partitions::TDataPartition,
  pub min_reservation_bytes: Option<i64>,
  pub initial_reservation_total_claims: Option<i64>,
  pub query_cache_param: Option<query_cache::TQueryCacheParam>,
}

impl TPlanFragment {
  pub fn new<F2, F4, F5, F7, F8, F9>(plan: F2, output_exprs: F4, output_sink: F5, partition: partitions::TDataPartition, min_reservation_bytes: F7, initial_reservation_total_claims: F8, query_cache_param: F9) -> TPlanFragment where F2: Into<Option<plan_nodes::TPlan>>, F4: Into<Option<Vec<exprs::TExpr>>>, F5: Into<Option<data_sinks::TDataSink>>, F7: Into<Option<i64>>, F8: Into<Option<i64>>, F9: Into<Option<query_cache::TQueryCacheParam>> {
    TPlanFragment {
      plan: plan.into(),
      output_exprs: output_exprs.into(),
      output_sink: output_sink.into(),
      partition,
      min_reservation_bytes: min_reservation_bytes.into(),
      initial_reservation_total_claims: initial_reservation_total_claims.into(),
      query_cache_param: query_cache_param.into(),
    }
  }
}

impl TSerializable for TPlanFragment {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<TPlanFragment> {
    i_prot.read_struct_begin()?;
    let mut f_2: Option<plan_nodes::TPlan> = None;
    let mut f_4: Option<Vec<exprs::TExpr>> = None;
    let mut f_5: Option<data_sinks::TDataSink> = None;
    let mut f_6: Option<partitions::TDataPartition> = None;
    let mut f_7: Option<i64> = None;
    let mut f_8: Option<i64> = None;
    let mut f_9: Option<query_cache::TQueryCacheParam> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        2 => {
          let val = plan_nodes::TPlan::read_from_in_protocol(i_prot)?;
          f_2 = Some(val);
        },
        4 => {
          let list_ident = i_prot.read_list_begin()?;
          let mut val: Vec<exprs::TExpr> = Vec::with_capacity(list_ident.size as usize);
          for _ in 0..list_ident.size {
            let list_elem_0 = exprs::TExpr::read_from_in_protocol(i_prot)?;
            val.push(list_elem_0);
          }
          i_prot.read_list_end()?;
          f_4 = Some(val);
        },
        5 => {
          let val = data_sinks::TDataSink::read_from_in_protocol(i_prot)?;
          f_5 = Some(val);
        },
        6 => {
          let val = partitions::TDataPartition::read_from_in_protocol(i_prot)?;
          f_6 = Some(val);
        },
        7 => {
          let val = i_prot.read_i64()?;
          f_7 = Some(val);
        },
        8 => {
          let val = i_prot.read_i64()?;
          f_8 = Some(val);
        },
        9 => {
          let val = query_cache::TQueryCacheParam::read_from_in_protocol(i_prot)?;
          f_9 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("TPlanFragment.partition", &f_6)?;
    let ret = TPlanFragment {
      plan: f_2,
      output_exprs: f_4,
      output_sink: f_5,
      partition: f_6.expect("auto-generated code should have checked for presence of required fields"),
      min_reservation_bytes: f_7,
      initial_reservation_total_claims: f_8,
      query_cache_param: f_9,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("TPlanFragment");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.plan {
      o_prot.write_field_begin(&TFieldIdentifier::new("plan", TType::Struct, 2))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.output_exprs {
      o_prot.write_field_begin(&TFieldIdentifier::new("output_exprs", TType::List, 4))?;
      o_prot.write_list_begin(&TListIdentifier::new(TType::Struct, fld_var.len() as i32))?;
      for e in fld_var {
        e.write_to_out_protocol(o_prot)?;
      }
      o_prot.write_list_end()?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.output_sink {
      o_prot.write_field_begin(&TFieldIdentifier::new("output_sink", TType::Struct, 5))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_begin(&TFieldIdentifier::new("partition", TType::Struct, 6))?;
    self.partition.write_to_out_protocol(o_prot)?;
    o_prot.write_field_end()?;
    if let Some(fld_var) = self.min_reservation_bytes {
      o_prot.write_field_begin(&TFieldIdentifier::new("min_reservation_bytes", TType::I64, 7))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.initial_reservation_total_claims {
      o_prot.write_field_begin(&TFieldIdentifier::new("initial_reservation_total_claims", TType::I64, 8))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.query_cache_param {
      o_prot.write_field_begin(&TFieldIdentifier::new("query_cache_param", TType::Struct, 9))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// TScanRangeLocation
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct TScanRangeLocation {
  pub server: types::TNetworkAddress,
  pub volume_id: Option<i32>,
  pub backend_id: Option<i64>,
}

impl TScanRangeLocation {
  pub fn new<F2, F3>(server: types::TNetworkAddress, volume_id: F2, backend_id: F3) -> TScanRangeLocation where F2: Into<Option<i32>>, F3: Into<Option<i64>> {
    TScanRangeLocation {
      server,
      volume_id: volume_id.into(),
      backend_id: backend_id.into(),
    }
  }
}

impl TSerializable for TScanRangeLocation {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<TScanRangeLocation> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<types::TNetworkAddress> = None;
    let mut f_2: Option<i32> = None;
    let mut f_3: Option<i64> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = types::TNetworkAddress::read_from_in_protocol(i_prot)?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_i32()?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_i64()?;
          f_3 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("TScanRangeLocation.server", &f_1)?;
    let ret = TScanRangeLocation {
      server: f_1.expect("auto-generated code should have checked for presence of required fields"),
      volume_id: f_2,
      backend_id: f_3,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("TScanRangeLocation");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("server", TType::Struct, 1))?;
    self.server.write_to_out_protocol(o_prot)?;
    o_prot.write_field_end()?;
    if let Some(fld_var) = self.volume_id {
      o_prot.write_field_begin(&TFieldIdentifier::new("volume_id", TType::I32, 2))?;
      o_prot.write_i32(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.backend_id {
      o_prot.write_field_begin(&TFieldIdentifier::new("backend_id", TType::I64, 3))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// TScanRangeLocations
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct TScanRangeLocations {
  pub scan_range: plan_nodes::TScanRange,
  pub locations: Option<Vec<TScanRangeLocation>>,
}

impl TScanRangeLocations {
  pub fn new<F2>(scan_range: plan_nodes::TScanRange, locations: F2) -> TScanRangeLocations where F2: Into<Option<Vec<TScanRangeLocation>>> {
    TScanRangeLocations {
      scan_range,
      locations: locations.into(),
    }
  }
}

impl TSerializable for TScanRangeLocations {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<TScanRangeLocations> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<plan_nodes::TScanRange> = None;
    let mut f_2: Option<Vec<TScanRangeLocation>> = Some(Vec::new());
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = plan_nodes::TScanRange::read_from_in_protocol(i_prot)?;
          f_1 = Some(val);
        },
        2 => {
          let list_ident = i_prot.read_list_begin()?;
          let mut val: Vec<TScanRangeLocation> = Vec::with_capacity(list_ident.size as usize);
          for _ in 0..list_ident.size {
            let list_elem_1 = TScanRangeLocation::read_from_in_protocol(i_prot)?;
            val.push(list_elem_1);
          }
          i_prot.read_list_end()?;
          f_2 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("TScanRangeLocations.scan_range", &f_1)?;
    let ret = TScanRangeLocations {
      scan_range: f_1.expect("auto-generated code should have checked for presence of required fields"),
      locations: f_2,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("TScanRangeLocations");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("scan_range", TType::Struct, 1))?;
    self.scan_range.write_to_out_protocol(o_prot)?;
    o_prot.write_field_end()?;
    if let Some(ref fld_var) = self.locations {
      o_prot.write_field_begin(&TFieldIdentifier::new("locations", TType::List, 2))?;
      o_prot.write_list_begin(&TListIdentifier::new(TType::Struct, fld_var.len() as i32))?;
      for e in fld_var {
        e.write_to_out_protocol(o_prot)?;
      }
      o_prot.write_list_end()?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

