// Autogenerated by Thrift Compiler (0.19.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_extern_crates)]
#![allow(clippy::too_many_arguments, clippy::type_complexity, clippy::vec_box, clippy::wrong_self_convention)]
#![cfg_attr(rustfmt, rustfmt_skip)]

use std::cell::RefCell;
use std::collections::{BTreeMap, BTreeSet};
use std::convert::{From, TryFrom};
use std::default::Default;
use std::error::Error;
use std::fmt;
use std::fmt::{Display, Formatter};
use std::rc::Rc;

use thrift::OrderedFloat;
use thrift::{ApplicationError, ApplicationErrorKind, ProtocolError, ProtocolErrorKind, TThriftClient};
use thrift::protocol::{TFieldIdentifier, TListIdentifier, TMapIdentifier, TMessageIdentifier, TMessageType, TInputProtocol, TOutputProtocol, TSerializable, TSetIdentifier, TStructIdentifier, TType};
use thrift::protocol::field_id;
use thrift::protocol::verify_expected_message_type;
use thrift::protocol::verify_expected_sequence_number;
use thrift::protocol::verify_expected_service_call;
use thrift::protocol::verify_required_field_exists;
use thrift::server::TProcessor;

use crate::metrics;

//
// TCounter
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct TCounter {
  pub name: String,
  pub type_: metrics::TUnit,
  pub value: i64,
  pub level: Option<i64>,
  pub description: Option<String>,
}

impl TCounter {
  pub fn new<F4, F5>(name: String, type_: metrics::TUnit, value: i64, level: F4, description: F5) -> TCounter where F4: Into<Option<i64>>, F5: Into<Option<String>> {
    TCounter {
      name,
      type_,
      value,
      level: level.into(),
      description: description.into(),
    }
  }
}

impl TSerializable for TCounter {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<TCounter> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<String> = None;
    let mut f_2: Option<metrics::TUnit> = None;
    let mut f_3: Option<i64> = None;
    let mut f_4: Option<i64> = None;
    let mut f_5: Option<String> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_string()?;
          f_1 = Some(val);
        },
        2 => {
          let val = metrics::TUnit::read_from_in_protocol(i_prot)?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_i64()?;
          f_3 = Some(val);
        },
        4 => {
          let val = i_prot.read_i64()?;
          f_4 = Some(val);
        },
        5 => {
          let val = i_prot.read_string()?;
          f_5 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("TCounter.name", &f_1)?;
    verify_required_field_exists("TCounter.type_", &f_2)?;
    verify_required_field_exists("TCounter.value", &f_3)?;
    let ret = TCounter {
      name: f_1.expect("auto-generated code should have checked for presence of required fields"),
      type_: f_2.expect("auto-generated code should have checked for presence of required fields"),
      value: f_3.expect("auto-generated code should have checked for presence of required fields"),
      level: f_4,
      description: f_5,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("TCounter");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("name", TType::String, 1))?;
    o_prot.write_string(&self.name)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("type", TType::I32, 2))?;
    self.type_.write_to_out_protocol(o_prot)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("value", TType::I64, 3))?;
    o_prot.write_i64(self.value)?;
    o_prot.write_field_end()?;
    if let Some(fld_var) = self.level {
      o_prot.write_field_begin(&TFieldIdentifier::new("level", TType::I64, 4))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.description {
      o_prot.write_field_begin(&TFieldIdentifier::new("description", TType::String, 5))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// TRuntimeProfileNode
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct TRuntimeProfileNode {
  pub name: String,
  pub num_children: i32,
  pub counters: Vec<TCounter>,
  pub metadata: i64,
  pub indent: bool,
  pub info_strings: BTreeMap<String, String>,
  pub info_strings_display_order: Vec<String>,
  pub child_counters_map: BTreeMap<String, BTreeSet<String>>,
  pub timestamp: i64,
  pub deprecated_is_sink: Option<bool>,
}

impl TRuntimeProfileNode {
  pub fn new<F10>(name: String, num_children: i32, counters: Vec<TCounter>, metadata: i64, indent: bool, info_strings: BTreeMap<String, String>, info_strings_display_order: Vec<String>, child_counters_map: BTreeMap<String, BTreeSet<String>>, timestamp: i64, deprecated_is_sink: F10) -> TRuntimeProfileNode where F10: Into<Option<bool>> {
    TRuntimeProfileNode {
      name,
      num_children,
      counters,
      metadata,
      indent,
      info_strings,
      info_strings_display_order,
      child_counters_map,
      timestamp,
      deprecated_is_sink: deprecated_is_sink.into(),
    }
  }
}

impl TSerializable for TRuntimeProfileNode {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<TRuntimeProfileNode> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<String> = None;
    let mut f_2: Option<i32> = None;
    let mut f_3: Option<Vec<TCounter>> = None;
    let mut f_4: Option<i64> = None;
    let mut f_5: Option<bool> = None;
    let mut f_6: Option<BTreeMap<String, String>> = None;
    let mut f_7: Option<Vec<String>> = None;
    let mut f_8: Option<BTreeMap<String, BTreeSet<String>>> = None;
    let mut f_9: Option<i64> = None;
    let mut f_10: Option<bool> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_string()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_i32()?;
          f_2 = Some(val);
        },
        3 => {
          let list_ident = i_prot.read_list_begin()?;
          let mut val: Vec<TCounter> = Vec::with_capacity(list_ident.size as usize);
          for _ in 0..list_ident.size {
            let list_elem_0 = TCounter::read_from_in_protocol(i_prot)?;
            val.push(list_elem_0);
          }
          i_prot.read_list_end()?;
          f_3 = Some(val);
        },
        4 => {
          let val = i_prot.read_i64()?;
          f_4 = Some(val);
        },
        5 => {
          let val = i_prot.read_bool()?;
          f_5 = Some(val);
        },
        6 => {
          let map_ident = i_prot.read_map_begin()?;
          let mut val: BTreeMap<String, String> = BTreeMap::new();
          for _ in 0..map_ident.size {
            let map_key_1 = i_prot.read_string()?;
            let map_val_2 = i_prot.read_string()?;
            val.insert(map_key_1, map_val_2);
          }
          i_prot.read_map_end()?;
          f_6 = Some(val);
        },
        7 => {
          let list_ident = i_prot.read_list_begin()?;
          let mut val: Vec<String> = Vec::with_capacity(list_ident.size as usize);
          for _ in 0..list_ident.size {
            let list_elem_3 = i_prot.read_string()?;
            val.push(list_elem_3);
          }
          i_prot.read_list_end()?;
          f_7 = Some(val);
        },
        8 => {
          let map_ident = i_prot.read_map_begin()?;
          let mut val: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
          for _ in 0..map_ident.size {
            let map_key_4 = i_prot.read_string()?;
            let set_ident = i_prot.read_set_begin()?;
            let mut map_val_5: BTreeSet<String> = BTreeSet::new();
            for _ in 0..set_ident.size {
              let set_elem_6 = i_prot.read_string()?;
              map_val_5.insert(set_elem_6);
            }
            i_prot.read_set_end()?;
            val.insert(map_key_4, map_val_5);
          }
          i_prot.read_map_end()?;
          f_8 = Some(val);
        },
        9 => {
          let val = i_prot.read_i64()?;
          f_9 = Some(val);
        },
        10 => {
          let val = i_prot.read_bool()?;
          f_10 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("TRuntimeProfileNode.name", &f_1)?;
    verify_required_field_exists("TRuntimeProfileNode.num_children", &f_2)?;
    verify_required_field_exists("TRuntimeProfileNode.counters", &f_3)?;
    verify_required_field_exists("TRuntimeProfileNode.metadata", &f_4)?;
    verify_required_field_exists("TRuntimeProfileNode.indent", &f_5)?;
    verify_required_field_exists("TRuntimeProfileNode.info_strings", &f_6)?;
    verify_required_field_exists("TRuntimeProfileNode.info_strings_display_order", &f_7)?;
    verify_required_field_exists("TRuntimeProfileNode.child_counters_map", &f_8)?;
    verify_required_field_exists("TRuntimeProfileNode.timestamp", &f_9)?;
    let ret = TRuntimeProfileNode {
      name: f_1.expect("auto-generated code should have checked for presence of required fields"),
      num_children: f_2.expect("auto-generated code should have checked for presence of required fields"),
      counters: f_3.expect("auto-generated code should have checked for presence of required fields"),
      metadata: f_4.expect("auto-generated code should have checked for presence of required fields"),
      indent: f_5.expect("auto-generated code should have checked for presence of required fields"),
      info_strings: f_6.expect("auto-generated code should have checked for presence of required fields"),
      info_strings_display_order: f_7.expect("auto-generated code should have checked for presence of required fields"),
      child_counters_map: f_8.expect("auto-generated code should have checked for presence of required fields"),
      timestamp: f_9.expect("auto-generated code should have checked for presence of required fields"),
      deprecated_is_sink: f_10,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("TRuntimeProfileNode");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("name", TType::String, 1))?;
    o_prot.write_string(&self.name)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("num_children", TType::I32, 2))?;
    o_prot.write_i32(self.num_children)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("counters", TType::List, 3))?;
    o_prot.write_list_begin(&TListIdentifier::new(TType::Struct, self.counters.len() as i32))?;
    for e in &self.counters {
      e.write_to_out_protocol(o_prot)?;
    }
    o_prot.write_list_end()?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("metadata", TType::I64, 4))?;
    o_prot.write_i64(self.metadata)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("indent", TType::Bool, 5))?;
    o_prot.write_bool(self.indent)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("info_strings", TType::Map, 6))?;
    o_prot.write_map_begin(&TMapIdentifier::new(TType::String, TType::String, self.info_strings.len() as i32))?;
    for (k, v) in &self.info_strings {
      o_prot.write_string(k)?;
      o_prot.write_string(v)?;
    }
    o_prot.write_map_end()?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("info_strings_display_order", TType::List, 7))?;
    o_prot.write_list_begin(&TListIdentifier::new(TType::String, self.info_strings_display_order.len() as i32))?;
    for e in &self.info_strings_display_order {
      o_prot.write_string(e)?;
    }
    o_prot.write_list_end()?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("child_counters_map", TType::Map, 8))?;
    o_prot.write_map_begin(&TMapIdentifier::new(TType::String, TType::Set, self.child_counters_map.len() as i32))?;
    for (k, v) in &self.child_counters_map {
      o_prot.write_string(k)?;
      o_prot.write_set_begin(&TSetIdentifier::new(TType::String, v.len() as i32))?;
      for e in v {
        o_prot.write_string(e)?;
      }
      o_prot.write_set_end()?;
    }
    o_prot.write_map_end()?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("timestamp", TType::I64, 9))?;
    o_prot.write_i64(self.timestamp)?;
    o_prot.write_field_end()?;
    if let Some(fld_var) = self.deprecated_is_sink {
      o_prot.write_field_begin(&TFieldIdentifier::new("deprecated_is_sink", TType::Bool, 10))?;
      o_prot.write_bool(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// TRuntimeProfileTree
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct TRuntimeProfileTree {
  pub nodes: Vec<TRuntimeProfileNode>,
}

impl TRuntimeProfileTree {
  pub fn new(nodes: Vec<TRuntimeProfileNode>) -> TRuntimeProfileTree {
    TRuntimeProfileTree {
      nodes,
    }
  }
}

impl TSerializable for TRuntimeProfileTree {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<TRuntimeProfileTree> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<Vec<TRuntimeProfileNode>> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let list_ident = i_prot.read_list_begin()?;
          let mut val: Vec<TRuntimeProfileNode> = Vec::with_capacity(list_ident.size as usize);
          for _ in 0..list_ident.size {
            let list_elem_7 = TRuntimeProfileNode::read_from_in_protocol(i_prot)?;
            val.push(list_elem_7);
          }
          i_prot.read_list_end()?;
          f_1 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("TRuntimeProfileTree.nodes", &f_1)?;
    let ret = TRuntimeProfileTree {
      nodes: f_1.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("TRuntimeProfileTree");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("nodes", TType::List, 1))?;
    o_prot.write_list_begin(&TListIdentifier::new(TType::Struct, self.nodes.len() as i32))?;
    for e in &self.nodes {
      e.write_to_out_protocol(o_prot)?;
    }
    o_prot.write_list_end()?;
    o_prot.write_field_end()?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

