// Autogenerated by Thrift Compiler (0.19.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_extern_crates)]
#![allow(clippy::too_many_arguments, clippy::type_complexity, clippy::vec_box, clippy::wrong_self_convention)]
#![cfg_attr(rustfmt, rustfmt_skip)]

use std::cell::RefCell;
use std::collections::{BTreeMap, BTreeSet};
use std::convert::{From, TryFrom};
use std::default::Default;
use std::error::Error;
use std::fmt;
use std::fmt::{Display, Formatter};
use std::rc::Rc;

use thrift::OrderedFloat;
use thrift::{ApplicationError, ApplicationErrorKind, ProtocolError, ProtocolErrorKind, TThriftClient};
use thrift::protocol::{TFieldIdentifier, TListIdentifier, TMapIdentifier, TMessageIdentifier, TMessageType, TInputProtocol, TOutputProtocol, TSerializable, TSetIdentifier, TStructIdentifier, TType};
use thrift::protocol::field_id;
use thrift::protocol::verify_expected_message_type;
use thrift::protocol::verify_expected_sequence_number;
use thrift::protocol::verify_expected_service_call;
use thrift::protocol::verify_required_field_exists;
use thrift::server::TProcessor;

#[derive(Copy, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct TStatusCode(pub i32);

impl TStatusCode {
  pub const OK: TStatusCode = TStatusCode(0);
  pub const CANCELLED: TStatusCode = TStatusCode(1);
  pub const ANALYSIS_ERROR: TStatusCode = TStatusCode(2);
  pub const NOT_IMPLEMENTED_ERROR: TStatusCode = TStatusCode(3);
  pub const RUNTIME_ERROR: TStatusCode = TStatusCode(4);
  pub const MEM_LIMIT_EXCEEDED: TStatusCode = TStatusCode(5);
  pub const INTERNAL_ERROR: TStatusCode = TStatusCode(6);
  pub const THRIFT_RPC_ERROR: TStatusCode = TStatusCode(7);
  pub const TIMEOUT: TStatusCode = TStatusCode(8);
  pub const LIMIT_REACH: TStatusCode = TStatusCode(9);
  pub const MEM_ALLOC_FAILED: TStatusCode = TStatusCode(11);
  pub const BUFFER_ALLOCATION_FAILED: TStatusCode = TStatusCode(12);
  pub const MINIMUM_RESERVATION_UNAVAILABLE: TStatusCode = TStatusCode(13);
  pub const PUBLISH_TIMEOUT: TStatusCode = TStatusCode(14);
  pub const LABEL_ALREADY_EXISTS: TStatusCode = TStatusCode(15);
  pub const TOO_MANY_TASKS: TStatusCode = TStatusCode(16);
  pub const END_OF_FILE: TStatusCode = TStatusCode(30);
  pub const NOT_FOUND: TStatusCode = TStatusCode(31);
  pub const CORRUPTION: TStatusCode = TStatusCode(32);
  pub const INVALID_ARGUMENT: TStatusCode = TStatusCode(33);
  pub const IO_ERROR: TStatusCode = TStatusCode(34);
  pub const ALREADY_EXIST: TStatusCode = TStatusCode(35);
  pub const NETWORK_ERROR: TStatusCode = TStatusCode(36);
  pub const ILLEGAL_STATE: TStatusCode = TStatusCode(37);
  pub const NOT_AUTHORIZED: TStatusCode = TStatusCode(38);
  pub const ABORTED: TStatusCode = TStatusCode(39);
  pub const DIRECTORY_NOT_EMPTY: TStatusCode = TStatusCode(40);
  pub const UNINITIALIZED: TStatusCode = TStatusCode(42);
  pub const INCOMPLETE: TStatusCode = TStatusCode(44);
  pub const OLAP_ERR_VERSION_ALREADY_MERGED: TStatusCode = TStatusCode(45);
  pub const DATA_QUALITY_ERROR: TStatusCode = TStatusCode(46);
  pub const INVALID_JSON_PATH: TStatusCode = TStatusCode(47);
  pub const JNI_ERROR: TStatusCode = TStatusCode(48);
  pub const BINLOG_DISABLE: TStatusCode = TStatusCode(60);
  pub const BINLOG_TOO_OLD_COMMIT_SEQ: TStatusCode = TStatusCode(61);
  pub const BINLOG_TOO_NEW_COMMIT_SEQ: TStatusCode = TStatusCode(62);
  pub const BINLOG_NOT_FOUND_DB: TStatusCode = TStatusCode(63);
  pub const BINLOG_NOT_FOUND_TABLE: TStatusCode = TStatusCode(64);
  pub const SNAPSHOT_NOT_EXIST: TStatusCode = TStatusCode(70);
  pub const HTTP_ERROR: TStatusCode = TStatusCode(71);
  pub const TABLET_MISSING: TStatusCode = TStatusCode(72);
  pub const NOT_MASTER: TStatusCode = TStatusCode(73);
  pub const OBTAIN_LOCK_FAILED: TStatusCode = TStatusCode(74);
  pub const SNAPSHOT_EXPIRED: TStatusCode = TStatusCode(75);
  pub const FINISHED: TStatusCode = TStatusCode(76);
  pub const DELETE_BITMAP_LOCK_ERROR: TStatusCode = TStatusCode(100);
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::OK,
    Self::CANCELLED,
    Self::ANALYSIS_ERROR,
    Self::NOT_IMPLEMENTED_ERROR,
    Self::RUNTIME_ERROR,
    Self::MEM_LIMIT_EXCEEDED,
    Self::INTERNAL_ERROR,
    Self::THRIFT_RPC_ERROR,
    Self::TIMEOUT,
    Self::LIMIT_REACH,
    Self::MEM_ALLOC_FAILED,
    Self::BUFFER_ALLOCATION_FAILED,
    Self::MINIMUM_RESERVATION_UNAVAILABLE,
    Self::PUBLISH_TIMEOUT,
    Self::LABEL_ALREADY_EXISTS,
    Self::TOO_MANY_TASKS,
    Self::END_OF_FILE,
    Self::NOT_FOUND,
    Self::CORRUPTION,
    Self::INVALID_ARGUMENT,
    Self::IO_ERROR,
    Self::ALREADY_EXIST,
    Self::NETWORK_ERROR,
    Self::ILLEGAL_STATE,
    Self::NOT_AUTHORIZED,
    Self::ABORTED,
    Self::DIRECTORY_NOT_EMPTY,
    Self::UNINITIALIZED,
    Self::INCOMPLETE,
    Self::OLAP_ERR_VERSION_ALREADY_MERGED,
    Self::DATA_QUALITY_ERROR,
    Self::INVALID_JSON_PATH,
    Self::JNI_ERROR,
    Self::BINLOG_DISABLE,
    Self::BINLOG_TOO_OLD_COMMIT_SEQ,
    Self::BINLOG_TOO_NEW_COMMIT_SEQ,
    Self::BINLOG_NOT_FOUND_DB,
    Self::BINLOG_NOT_FOUND_TABLE,
    Self::SNAPSHOT_NOT_EXIST,
    Self::HTTP_ERROR,
    Self::TABLET_MISSING,
    Self::NOT_MASTER,
    Self::OBTAIN_LOCK_FAILED,
    Self::SNAPSHOT_EXPIRED,
    Self::FINISHED,
    Self::DELETE_BITMAP_LOCK_ERROR,
  ];
}

impl TSerializable for TStatusCode {
  #[allow(clippy::trivially_copy_pass_by_ref)]
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    o_prot.write_i32(self.0)
  }
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<TStatusCode> {
    let enum_value = i_prot.read_i32()?;
    Ok(TStatusCode::from(enum_value))
  }
}

impl From<i32> for TStatusCode {
  fn from(i: i32) -> Self {
    match i {
      0 => TStatusCode::OK,
      1 => TStatusCode::CANCELLED,
      2 => TStatusCode::ANALYSIS_ERROR,
      3 => TStatusCode::NOT_IMPLEMENTED_ERROR,
      4 => TStatusCode::RUNTIME_ERROR,
      5 => TStatusCode::MEM_LIMIT_EXCEEDED,
      6 => TStatusCode::INTERNAL_ERROR,
      7 => TStatusCode::THRIFT_RPC_ERROR,
      8 => TStatusCode::TIMEOUT,
      9 => TStatusCode::LIMIT_REACH,
      11 => TStatusCode::MEM_ALLOC_FAILED,
      12 => TStatusCode::BUFFER_ALLOCATION_FAILED,
      13 => TStatusCode::MINIMUM_RESERVATION_UNAVAILABLE,
      14 => TStatusCode::PUBLISH_TIMEOUT,
      15 => TStatusCode::LABEL_ALREADY_EXISTS,
      16 => TStatusCode::TOO_MANY_TASKS,
      30 => TStatusCode::END_OF_FILE,
      31 => TStatusCode::NOT_FOUND,
      32 => TStatusCode::CORRUPTION,
      33 => TStatusCode::INVALID_ARGUMENT,
      34 => TStatusCode::IO_ERROR,
      35 => TStatusCode::ALREADY_EXIST,
      36 => TStatusCode::NETWORK_ERROR,
      37 => TStatusCode::ILLEGAL_STATE,
      38 => TStatusCode::NOT_AUTHORIZED,
      39 => TStatusCode::ABORTED,
      40 => TStatusCode::DIRECTORY_NOT_EMPTY,
      42 => TStatusCode::UNINITIALIZED,
      44 => TStatusCode::INCOMPLETE,
      45 => TStatusCode::OLAP_ERR_VERSION_ALREADY_MERGED,
      46 => TStatusCode::DATA_QUALITY_ERROR,
      47 => TStatusCode::INVALID_JSON_PATH,
      48 => TStatusCode::JNI_ERROR,
      60 => TStatusCode::BINLOG_DISABLE,
      61 => TStatusCode::BINLOG_TOO_OLD_COMMIT_SEQ,
      62 => TStatusCode::BINLOG_TOO_NEW_COMMIT_SEQ,
      63 => TStatusCode::BINLOG_NOT_FOUND_DB,
      64 => TStatusCode::BINLOG_NOT_FOUND_TABLE,
      70 => TStatusCode::SNAPSHOT_NOT_EXIST,
      71 => TStatusCode::HTTP_ERROR,
      72 => TStatusCode::TABLET_MISSING,
      73 => TStatusCode::NOT_MASTER,
      74 => TStatusCode::OBTAIN_LOCK_FAILED,
      75 => TStatusCode::SNAPSHOT_EXPIRED,
      76 => TStatusCode::FINISHED,
      100 => TStatusCode::DELETE_BITMAP_LOCK_ERROR,
      _ => TStatusCode(i)
    }
  }
}

impl From<&i32> for TStatusCode {
  fn from(i: &i32) -> Self {
    TStatusCode::from(*i)
  }
}

impl From<TStatusCode> for i32 {
  fn from(e: TStatusCode) -> i32 {
    e.0
  }
}

impl From<&TStatusCode> for i32 {
  fn from(e: &TStatusCode) -> i32 {
    e.0
  }
}

//
// TStatus
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct TStatus {
  pub status_code: TStatusCode,
  pub error_msgs: Option<Vec<String>>,
}

impl TStatus {
  pub fn new<F2>(status_code: TStatusCode, error_msgs: F2) -> TStatus where F2: Into<Option<Vec<String>>> {
    TStatus {
      status_code,
      error_msgs: error_msgs.into(),
    }
  }
}

impl TSerializable for TStatus {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<TStatus> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<TStatusCode> = None;
    let mut f_2: Option<Vec<String>> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = TStatusCode::read_from_in_protocol(i_prot)?;
          f_1 = Some(val);
        },
        2 => {
          let list_ident = i_prot.read_list_begin()?;
          let mut val: Vec<String> = Vec::with_capacity(list_ident.size as usize);
          for _ in 0..list_ident.size {
            let list_elem_0 = i_prot.read_string()?;
            val.push(list_elem_0);
          }
          i_prot.read_list_end()?;
          f_2 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("TStatus.status_code", &f_1)?;
    let ret = TStatus {
      status_code: f_1.expect("auto-generated code should have checked for presence of required fields"),
      error_msgs: f_2,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("TStatus");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("status_code", TType::I32, 1))?;
    self.status_code.write_to_out_protocol(o_prot)?;
    o_prot.write_field_end()?;
    if let Some(ref fld_var) = self.error_msgs {
      o_prot.write_field_begin(&TFieldIdentifier::new("error_msgs", TType::List, 2))?;
      o_prot.write_list_begin(&TListIdentifier::new(TType::String, fld_var.len() as i32))?;
      for e in fld_var {
        o_prot.write_string(e)?;
      }
      o_prot.write_list_end()?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

