// Autogenerated by Thrift Compiler (0.22.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_extern_crates)]
#![allow(clippy::too_many_arguments, clippy::type_complexity, clippy::vec_box, clippy::wrong_self_convention)]
#![cfg_attr(rustfmt, rustfmt_skip)]

use std::cell::RefCell;
use std::collections::{BTreeMap, BTreeSet};
use std::convert::{From, TryFrom};
use std::default::Default;
use std::error::Error;
use std::fmt;
use std::fmt::{Display, Formatter};
use std::rc::Rc;

use thrift::OrderedFloat;
use thrift::{ApplicationError, ApplicationErrorKind, ProtocolError, ProtocolErrorKind, TThriftClient};
use thrift::protocol::{TFieldIdentifier, TListIdentifier, TMapIdentifier, TMessageIdentifier, TMessageType, TInputProtocol, TOutputProtocol, TSerializable, TSetIdentifier, TStructIdentifier, TType};
use thrift::protocol::field_id;
use thrift::protocol::verify_expected_message_type;
use thrift::protocol::verify_expected_sequence_number;
use thrift::protocol::verify_expected_service_call;
use thrift::protocol::verify_required_field_exists;
use thrift::server::TProcessor;

use crate::types;

//
// TCell
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct TCell {
  pub bool_val: Option<bool>,
  pub int_val: Option<i32>,
  pub long_val: Option<i64>,
  pub double_val: Option<OrderedFloat<f64>>,
  pub string_val: Option<String>,
  pub is_null: Option<bool>,
}

impl TCell {
  pub fn new<F1, F2, F3, F4, F5, F6>(bool_val: F1, int_val: F2, long_val: F3, double_val: F4, string_val: F5, is_null: F6) -> TCell where F1: Into<Option<bool>>, F2: Into<Option<i32>>, F3: Into<Option<i64>>, F4: Into<Option<OrderedFloat<f64>>>, F5: Into<Option<String>>, F6: Into<Option<bool>> {
    TCell {
      bool_val: bool_val.into(),
      int_val: int_val.into(),
      long_val: long_val.into(),
      double_val: double_val.into(),
      string_val: string_val.into(),
      is_null: is_null.into(),
    }
  }
}

impl TSerializable for TCell {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<TCell> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<bool> = None;
    let mut f_2: Option<i32> = None;
    let mut f_3: Option<i64> = None;
    let mut f_4: Option<OrderedFloat<f64>> = None;
    let mut f_5: Option<String> = None;
    let mut f_6: Option<bool> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_bool()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_i32()?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_i64()?;
          f_3 = Some(val);
        },
        4 => {
          let val = OrderedFloat::from(i_prot.read_double()?);
          f_4 = Some(val);
        },
        5 => {
          let val = i_prot.read_string()?;
          f_5 = Some(val);
        },
        6 => {
          let val = i_prot.read_bool()?;
          f_6 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = TCell {
      bool_val: f_1,
      int_val: f_2,
      long_val: f_3,
      double_val: f_4,
      string_val: f_5,
      is_null: f_6,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("TCell");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(fld_var) = self.bool_val {
      o_prot.write_field_begin(&TFieldIdentifier::new("boolVal", TType::Bool, 1))?;
      o_prot.write_bool(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.int_val {
      o_prot.write_field_begin(&TFieldIdentifier::new("intVal", TType::I32, 2))?;
      o_prot.write_i32(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.long_val {
      o_prot.write_field_begin(&TFieldIdentifier::new("longVal", TType::I64, 3))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.double_val {
      o_prot.write_field_begin(&TFieldIdentifier::new("doubleVal", TType::Double, 4))?;
      o_prot.write_double(fld_var.into())?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.string_val {
      o_prot.write_field_begin(&TFieldIdentifier::new("stringVal", TType::String, 5))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.is_null {
      o_prot.write_field_begin(&TFieldIdentifier::new("isNull", TType::Bool, 6))?;
      o_prot.write_bool(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// TResultRow
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct TResultRow {
  pub col_vals: Option<Vec<TCell>>,
}

impl TResultRow {
  pub fn new<F1>(col_vals: F1) -> TResultRow where F1: Into<Option<Vec<TCell>>> {
    TResultRow {
      col_vals: col_vals.into(),
    }
  }
}

impl TSerializable for TResultRow {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<TResultRow> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<Vec<TCell>> = Some(Vec::new());
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let list_ident = i_prot.read_list_begin()?;
          let mut val: Vec<TCell> = Vec::with_capacity(list_ident.size as usize);
          for _ in 0..list_ident.size {
            let list_elem_0 = TCell::read_from_in_protocol(i_prot)?;
            val.push(list_elem_0);
          }
          i_prot.read_list_end()?;
          f_1 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = TResultRow {
      col_vals: f_1,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("TResultRow");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.col_vals {
      o_prot.write_field_begin(&TFieldIdentifier::new("colVals", TType::List, 1))?;
      o_prot.write_list_begin(&TListIdentifier::new(TType::Struct, fld_var.len() as i32))?;
      for e in fld_var {
        e.write_to_out_protocol(o_prot)?;
      }
      o_prot.write_list_end()?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// TRow
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct TRow {
  pub column_value: Option<Vec<TCell>>,
}

impl TRow {
  pub fn new<F1>(column_value: F1) -> TRow where F1: Into<Option<Vec<TCell>>> {
    TRow {
      column_value: column_value.into(),
    }
  }
}

impl TSerializable for TRow {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<TRow> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<Vec<TCell>> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let list_ident = i_prot.read_list_begin()?;
          let mut val: Vec<TCell> = Vec::with_capacity(list_ident.size as usize);
          for _ in 0..list_ident.size {
            let list_elem_1 = TCell::read_from_in_protocol(i_prot)?;
            val.push(list_elem_1);
          }
          i_prot.read_list_end()?;
          f_1 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = TRow {
      column_value: f_1,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("TRow");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.column_value {
      o_prot.write_field_begin(&TFieldIdentifier::new("column_value", TType::List, 1))?;
      o_prot.write_list_begin(&TListIdentifier::new(TType::Struct, fld_var.len() as i32))?;
      for e in fld_var {
        e.write_to_out_protocol(o_prot)?;
      }
      o_prot.write_list_end()?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// TResultBatch
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct TResultBatch {
  pub rows: Vec<Vec<u8>>,
  pub is_compressed: bool,
  pub packet_seq: i64,
  pub attached_infos: Option<BTreeMap<String, String>>,
}

impl TResultBatch {
  pub fn new<F4>(rows: Vec<Vec<u8>>, is_compressed: bool, packet_seq: i64, attached_infos: F4) -> TResultBatch where F4: Into<Option<BTreeMap<String, String>>> {
    TResultBatch {
      rows,
      is_compressed,
      packet_seq,
      attached_infos: attached_infos.into(),
    }
  }
}

impl TSerializable for TResultBatch {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<TResultBatch> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<Vec<Vec<u8>>> = None;
    let mut f_2: Option<bool> = None;
    let mut f_3: Option<i64> = None;
    let mut f_4: Option<BTreeMap<String, String>> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let list_ident = i_prot.read_list_begin()?;
          let mut val: Vec<Vec<u8>> = Vec::with_capacity(list_ident.size as usize);
          for _ in 0..list_ident.size {
            let list_elem_2 = i_prot.read_bytes()?;
            val.push(list_elem_2);
          }
          i_prot.read_list_end()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_bool()?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_i64()?;
          f_3 = Some(val);
        },
        4 => {
          let map_ident = i_prot.read_map_begin()?;
          let mut val: BTreeMap<String, String> = BTreeMap::new();
          for _ in 0..map_ident.size {
            let map_key_3 = i_prot.read_string()?;
            let map_val_4 = i_prot.read_string()?;
            val.insert(map_key_3, map_val_4);
          }
          i_prot.read_map_end()?;
          f_4 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("TResultBatch.rows", &f_1)?;
    verify_required_field_exists("TResultBatch.is_compressed", &f_2)?;
    verify_required_field_exists("TResultBatch.packet_seq", &f_3)?;
    let ret = TResultBatch {
      rows: f_1.expect("auto-generated code should have checked for presence of required fields"),
      is_compressed: f_2.expect("auto-generated code should have checked for presence of required fields"),
      packet_seq: f_3.expect("auto-generated code should have checked for presence of required fields"),
      attached_infos: f_4,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("TResultBatch");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("rows", TType::List, 1))?;
    o_prot.write_list_begin(&TListIdentifier::new(TType::String, self.rows.len() as i32))?;
    for e in &self.rows {
      o_prot.write_bytes(e)?;
    }
    o_prot.write_list_end()?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("is_compressed", TType::Bool, 2))?;
    o_prot.write_bool(self.is_compressed)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("packet_seq", TType::I64, 3))?;
    o_prot.write_i64(self.packet_seq)?;
    o_prot.write_field_end()?;
    if let Some(ref fld_var) = self.attached_infos {
      o_prot.write_field_begin(&TFieldIdentifier::new("attached_infos", TType::Map, 4))?;
      o_prot.write_map_begin(&TMapIdentifier::new(TType::String, TType::String, fld_var.len() as i32))?;
      for (k, v) in fld_var {
        o_prot.write_string(k)?;
        o_prot.write_string(v)?;
      }
      o_prot.write_map_end()?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

