// Autogenerated by Thrift Compiler (0.22.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_extern_crates)]
#![allow(clippy::too_many_arguments, clippy::type_complexity, clippy::vec_box, clippy::wrong_self_convention)]
#![cfg_attr(rustfmt, rustfmt_skip)]

use std::cell::RefCell;
use std::collections::{BTreeMap, BTreeSet};
use std::convert::{From, TryFrom};
use std::default::Default;
use std::error::Error;
use std::fmt;
use std::fmt::{Display, Formatter};
use std::rc::Rc;

use thrift::OrderedFloat;
use thrift::{ApplicationError, ApplicationErrorKind, ProtocolError, ProtocolErrorKind, TThriftClient};
use thrift::protocol::{TFieldIdentifier, TListIdentifier, TMapIdentifier, TMessageIdentifier, TMessageType, TInputProtocol, TOutputProtocol, TSerializable, TSetIdentifier, TStructIdentifier, TType};
use thrift::protocol::field_id;
use thrift::protocol::verify_expected_message_type;
use thrift::protocol::verify_expected_sequence_number;
use thrift::protocol::verify_expected_service_call;
use thrift::protocol::verify_required_field_exists;
use thrift::server::TProcessor;

#[derive(Copy, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct TExprOpcode(pub i32);

impl TExprOpcode {
  pub const INVALID_OPCODE: TExprOpcode = TExprOpcode(0);
  pub const COMPOUND_NOT: TExprOpcode = TExprOpcode(1);
  pub const COMPOUND_AND: TExprOpcode = TExprOpcode(2);
  pub const COMPOUND_OR: TExprOpcode = TExprOpcode(3);
  pub const CAST: TExprOpcode = TExprOpcode(4);
  pub const FILTER_IN: TExprOpcode = TExprOpcode(5);
  pub const FILTER_NOT_IN: TExprOpcode = TExprOpcode(6);
  pub const FILTER_NEW_IN: TExprOpcode = TExprOpcode(7);
  pub const FILTER_NEW_NOT_IN: TExprOpcode = TExprOpcode(8);
  pub const EQ: TExprOpcode = TExprOpcode(9);
  pub const NE: TExprOpcode = TExprOpcode(10);
  pub const LT: TExprOpcode = TExprOpcode(11);
  pub const LE: TExprOpcode = TExprOpcode(12);
  pub const GT: TExprOpcode = TExprOpcode(13);
  pub const GE: TExprOpcode = TExprOpcode(14);
  pub const CONDITION_IF: TExprOpcode = TExprOpcode(15);
  pub const CONDITION_NULLIF: TExprOpcode = TExprOpcode(16);
  pub const CONDITION_IFNULL: TExprOpcode = TExprOpcode(17);
  pub const CONDITION_COALESCE: TExprOpcode = TExprOpcode(18);
  pub const TIMESTAMP_DATE_FORMAT: TExprOpcode = TExprOpcode(19);
  pub const TIMESTAMP_DAYOFMONTH: TExprOpcode = TExprOpcode(20);
  pub const TIMESTAMP_DAYOFYEAR: TExprOpcode = TExprOpcode(21);
  pub const TIMESTAMP_DAYS_ADD: TExprOpcode = TExprOpcode(22);
  pub const TIMESTAMP_DAYS_SUB: TExprOpcode = TExprOpcode(23);
  pub const TIMESTAMP_DAY_NAME: TExprOpcode = TExprOpcode(24);
  pub const TIMESTAMP_DIFF: TExprOpcode = TExprOpcode(25);
  pub const TIMESTAMP_FROM_DAYS: TExprOpcode = TExprOpcode(26);
  pub const TIMESTAMP_HOUR: TExprOpcode = TExprOpcode(27);
  pub const TIMESTAMP_HOURS_ADD: TExprOpcode = TExprOpcode(28);
  pub const TIMESTAMP_HOURS_SUB: TExprOpcode = TExprOpcode(29);
  pub const TIMESTAMP_MICROSECOND: TExprOpcode = TExprOpcode(30);
  pub const TIMESTAMP_MICROSECONDS_ADD: TExprOpcode = TExprOpcode(31);
  pub const TIMESTAMP_MICROSECONDS_SUB: TExprOpcode = TExprOpcode(32);
  pub const TIMESTAMP_MINUTE: TExprOpcode = TExprOpcode(33);
  pub const TIMESTAMP_MINUTES_ADD: TExprOpcode = TExprOpcode(34);
  pub const TIMESTAMP_MINUTES_SUB: TExprOpcode = TExprOpcode(35);
  pub const TIMESTAMP_MONTH: TExprOpcode = TExprOpcode(36);
  pub const TIMESTAMP_MONTHS_ADD: TExprOpcode = TExprOpcode(37);
  pub const TIMESTAMP_MONTHS_SUB: TExprOpcode = TExprOpcode(38);
  pub const TIMESTAMP_MONT_NAME: TExprOpcode = TExprOpcode(39);
  pub const TIMESTAMP_NOW: TExprOpcode = TExprOpcode(40);
  pub const TIMESTAMP_SECOND: TExprOpcode = TExprOpcode(41);
  pub const TIMESTAMP_SECONDS_ADD: TExprOpcode = TExprOpcode(42);
  pub const TIMESTAMP_SECONDS_SUB: TExprOpcode = TExprOpcode(43);
  pub const TIMESTAMP_STR_TO_DATE: TExprOpcode = TExprOpcode(44);
  pub const TIMESTAMP_TO_DATE: TExprOpcode = TExprOpcode(45);
  pub const TIMESTAMP_TO_DAYS: TExprOpcode = TExprOpcode(46);
  pub const TIMESTAMP_WEEKOFYEAR: TExprOpcode = TExprOpcode(47);
  pub const TIMESTAMP_WEEKS_ADD: TExprOpcode = TExprOpcode(48);
  pub const TIMESTAMP_WEEKS_SUB: TExprOpcode = TExprOpcode(49);
  pub const TIMESTAMP_YEAR: TExprOpcode = TExprOpcode(50);
  pub const TIMESTAMP_YEARS_ADD: TExprOpcode = TExprOpcode(51);
  pub const TIMESTAMP_YEARS_SUB: TExprOpcode = TExprOpcode(52);
  pub const ADD: TExprOpcode = TExprOpcode(53);
  pub const SUBTRACT: TExprOpcode = TExprOpcode(54);
  pub const MULTIPLY: TExprOpcode = TExprOpcode(55);
  pub const DIVIDE: TExprOpcode = TExprOpcode(56);
  pub const INT_DIVIDE: TExprOpcode = TExprOpcode(57);
  pub const MOD: TExprOpcode = TExprOpcode(58);
  pub const BITAND: TExprOpcode = TExprOpcode(59);
  pub const BITOR: TExprOpcode = TExprOpcode(60);
  pub const BITXOR: TExprOpcode = TExprOpcode(61);
  pub const BITNOT: TExprOpcode = TExprOpcode(62);
  pub const FACTORIAL: TExprOpcode = TExprOpcode(63);
  pub const LAST_OPCODE: TExprOpcode = TExprOpcode(64);
  pub const EQ_FOR_NULL: TExprOpcode = TExprOpcode(65);
  pub const RT_FILTER: TExprOpcode = TExprOpcode(66);
  pub const MATCH_ANY: TExprOpcode = TExprOpcode(67);
  pub const MATCH_ALL: TExprOpcode = TExprOpcode(68);
  pub const MATCH_PHRASE: TExprOpcode = TExprOpcode(69);
  pub const MATCH_ELEMENT_EQ: TExprOpcode = TExprOpcode(70);
  pub const MATCH_ELEMENT_LT: TExprOpcode = TExprOpcode(71);
  pub const MATCH_ELEMENT_GT: TExprOpcode = TExprOpcode(72);
  pub const MATCH_ELEMENT_LE: TExprOpcode = TExprOpcode(73);
  pub const MATCH_ELEMENT_GE: TExprOpcode = TExprOpcode(74);
  pub const MATCH_PHRASE_PREFIX: TExprOpcode = TExprOpcode(75);
  pub const MATCH_REGEXP: TExprOpcode = TExprOpcode(76);
  pub const MATCH_PHRASE_EDGE: TExprOpcode = TExprOpcode(77);
  pub const TRY_CAST: TExprOpcode = TExprOpcode(78);
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::INVALID_OPCODE,
    Self::COMPOUND_NOT,
    Self::COMPOUND_AND,
    Self::COMPOUND_OR,
    Self::CAST,
    Self::FILTER_IN,
    Self::FILTER_NOT_IN,
    Self::FILTER_NEW_IN,
    Self::FILTER_NEW_NOT_IN,
    Self::EQ,
    Self::NE,
    Self::LT,
    Self::LE,
    Self::GT,
    Self::GE,
    Self::CONDITION_IF,
    Self::CONDITION_NULLIF,
    Self::CONDITION_IFNULL,
    Self::CONDITION_COALESCE,
    Self::TIMESTAMP_DATE_FORMAT,
    Self::TIMESTAMP_DAYOFMONTH,
    Self::TIMESTAMP_DAYOFYEAR,
    Self::TIMESTAMP_DAYS_ADD,
    Self::TIMESTAMP_DAYS_SUB,
    Self::TIMESTAMP_DAY_NAME,
    Self::TIMESTAMP_DIFF,
    Self::TIMESTAMP_FROM_DAYS,
    Self::TIMESTAMP_HOUR,
    Self::TIMESTAMP_HOURS_ADD,
    Self::TIMESTAMP_HOURS_SUB,
    Self::TIMESTAMP_MICROSECOND,
    Self::TIMESTAMP_MICROSECONDS_ADD,
    Self::TIMESTAMP_MICROSECONDS_SUB,
    Self::TIMESTAMP_MINUTE,
    Self::TIMESTAMP_MINUTES_ADD,
    Self::TIMESTAMP_MINUTES_SUB,
    Self::TIMESTAMP_MONTH,
    Self::TIMESTAMP_MONTHS_ADD,
    Self::TIMESTAMP_MONTHS_SUB,
    Self::TIMESTAMP_MONT_NAME,
    Self::TIMESTAMP_NOW,
    Self::TIMESTAMP_SECOND,
    Self::TIMESTAMP_SECONDS_ADD,
    Self::TIMESTAMP_SECONDS_SUB,
    Self::TIMESTAMP_STR_TO_DATE,
    Self::TIMESTAMP_TO_DATE,
    Self::TIMESTAMP_TO_DAYS,
    Self::TIMESTAMP_WEEKOFYEAR,
    Self::TIMESTAMP_WEEKS_ADD,
    Self::TIMESTAMP_WEEKS_SUB,
    Self::TIMESTAMP_YEAR,
    Self::TIMESTAMP_YEARS_ADD,
    Self::TIMESTAMP_YEARS_SUB,
    Self::ADD,
    Self::SUBTRACT,
    Self::MULTIPLY,
    Self::DIVIDE,
    Self::INT_DIVIDE,
    Self::MOD,
    Self::BITAND,
    Self::BITOR,
    Self::BITXOR,
    Self::BITNOT,
    Self::FACTORIAL,
    Self::LAST_OPCODE,
    Self::EQ_FOR_NULL,
    Self::RT_FILTER,
    Self::MATCH_ANY,
    Self::MATCH_ALL,
    Self::MATCH_PHRASE,
    Self::MATCH_ELEMENT_EQ,
    Self::MATCH_ELEMENT_LT,
    Self::MATCH_ELEMENT_GT,
    Self::MATCH_ELEMENT_LE,
    Self::MATCH_ELEMENT_GE,
    Self::MATCH_PHRASE_PREFIX,
    Self::MATCH_REGEXP,
    Self::MATCH_PHRASE_EDGE,
    Self::TRY_CAST,
  ];
}

impl TSerializable for TExprOpcode {
  #[allow(clippy::trivially_copy_pass_by_ref)]
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    o_prot.write_i32(self.0)
  }
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<TExprOpcode> {
    let enum_value = i_prot.read_i32()?;
    Ok(TExprOpcode::from(enum_value))
  }
}

impl From<i32> for TExprOpcode {
  fn from(i: i32) -> Self {
    match i {
      0 => TExprOpcode::INVALID_OPCODE,
      1 => TExprOpcode::COMPOUND_NOT,
      2 => TExprOpcode::COMPOUND_AND,
      3 => TExprOpcode::COMPOUND_OR,
      4 => TExprOpcode::CAST,
      5 => TExprOpcode::FILTER_IN,
      6 => TExprOpcode::FILTER_NOT_IN,
      7 => TExprOpcode::FILTER_NEW_IN,
      8 => TExprOpcode::FILTER_NEW_NOT_IN,
      9 => TExprOpcode::EQ,
      10 => TExprOpcode::NE,
      11 => TExprOpcode::LT,
      12 => TExprOpcode::LE,
      13 => TExprOpcode::GT,
      14 => TExprOpcode::GE,
      15 => TExprOpcode::CONDITION_IF,
      16 => TExprOpcode::CONDITION_NULLIF,
      17 => TExprOpcode::CONDITION_IFNULL,
      18 => TExprOpcode::CONDITION_COALESCE,
      19 => TExprOpcode::TIMESTAMP_DATE_FORMAT,
      20 => TExprOpcode::TIMESTAMP_DAYOFMONTH,
      21 => TExprOpcode::TIMESTAMP_DAYOFYEAR,
      22 => TExprOpcode::TIMESTAMP_DAYS_ADD,
      23 => TExprOpcode::TIMESTAMP_DAYS_SUB,
      24 => TExprOpcode::TIMESTAMP_DAY_NAME,
      25 => TExprOpcode::TIMESTAMP_DIFF,
      26 => TExprOpcode::TIMESTAMP_FROM_DAYS,
      27 => TExprOpcode::TIMESTAMP_HOUR,
      28 => TExprOpcode::TIMESTAMP_HOURS_ADD,
      29 => TExprOpcode::TIMESTAMP_HOURS_SUB,
      30 => TExprOpcode::TIMESTAMP_MICROSECOND,
      31 => TExprOpcode::TIMESTAMP_MICROSECONDS_ADD,
      32 => TExprOpcode::TIMESTAMP_MICROSECONDS_SUB,
      33 => TExprOpcode::TIMESTAMP_MINUTE,
      34 => TExprOpcode::TIMESTAMP_MINUTES_ADD,
      35 => TExprOpcode::TIMESTAMP_MINUTES_SUB,
      36 => TExprOpcode::TIMESTAMP_MONTH,
      37 => TExprOpcode::TIMESTAMP_MONTHS_ADD,
      38 => TExprOpcode::TIMESTAMP_MONTHS_SUB,
      39 => TExprOpcode::TIMESTAMP_MONT_NAME,
      40 => TExprOpcode::TIMESTAMP_NOW,
      41 => TExprOpcode::TIMESTAMP_SECOND,
      42 => TExprOpcode::TIMESTAMP_SECONDS_ADD,
      43 => TExprOpcode::TIMESTAMP_SECONDS_SUB,
      44 => TExprOpcode::TIMESTAMP_STR_TO_DATE,
      45 => TExprOpcode::TIMESTAMP_TO_DATE,
      46 => TExprOpcode::TIMESTAMP_TO_DAYS,
      47 => TExprOpcode::TIMESTAMP_WEEKOFYEAR,
      48 => TExprOpcode::TIMESTAMP_WEEKS_ADD,
      49 => TExprOpcode::TIMESTAMP_WEEKS_SUB,
      50 => TExprOpcode::TIMESTAMP_YEAR,
      51 => TExprOpcode::TIMESTAMP_YEARS_ADD,
      52 => TExprOpcode::TIMESTAMP_YEARS_SUB,
      53 => TExprOpcode::ADD,
      54 => TExprOpcode::SUBTRACT,
      55 => TExprOpcode::MULTIPLY,
      56 => TExprOpcode::DIVIDE,
      57 => TExprOpcode::INT_DIVIDE,
      58 => TExprOpcode::MOD,
      59 => TExprOpcode::BITAND,
      60 => TExprOpcode::BITOR,
      61 => TExprOpcode::BITXOR,
      62 => TExprOpcode::BITNOT,
      63 => TExprOpcode::FACTORIAL,
      64 => TExprOpcode::LAST_OPCODE,
      65 => TExprOpcode::EQ_FOR_NULL,
      66 => TExprOpcode::RT_FILTER,
      67 => TExprOpcode::MATCH_ANY,
      68 => TExprOpcode::MATCH_ALL,
      69 => TExprOpcode::MATCH_PHRASE,
      70 => TExprOpcode::MATCH_ELEMENT_EQ,
      71 => TExprOpcode::MATCH_ELEMENT_LT,
      72 => TExprOpcode::MATCH_ELEMENT_GT,
      73 => TExprOpcode::MATCH_ELEMENT_LE,
      74 => TExprOpcode::MATCH_ELEMENT_GE,
      75 => TExprOpcode::MATCH_PHRASE_PREFIX,
      76 => TExprOpcode::MATCH_REGEXP,
      77 => TExprOpcode::MATCH_PHRASE_EDGE,
      78 => TExprOpcode::TRY_CAST,
      _ => TExprOpcode(i)
    }
  }
}

impl From<&i32> for TExprOpcode {
  fn from(i: &i32) -> Self {
    TExprOpcode::from(*i)
  }
}

impl From<TExprOpcode> for i32 {
  fn from(e: TExprOpcode) -> i32 {
    e.0
  }
}

impl From<&TExprOpcode> for i32 {
  fn from(e: &TExprOpcode) -> i32 {
    e.0
  }
}

