// Autogenerated by Thrift Compiler (0.22.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_extern_crates)]
#![allow(clippy::too_many_arguments, clippy::type_complexity, clippy::vec_box, clippy::wrong_self_convention)]
#![cfg_attr(rustfmt, rustfmt_skip)]

use std::cell::RefCell;
use std::collections::{BTreeMap, BTreeSet};
use std::convert::{From, TryFrom};
use std::default::Default;
use std::error::Error;
use std::fmt;
use std::fmt::{Display, Formatter};
use std::rc::Rc;

use thrift::OrderedFloat;
use thrift::{ApplicationError, ApplicationErrorKind, ProtocolError, ProtocolErrorKind, TThriftClient};
use thrift::protocol::{TFieldIdentifier, TListIdentifier, TMapIdentifier, TMessageIdentifier, TMessageType, TInputProtocol, TOutputProtocol, TSerializable, TSetIdentifier, TStructIdentifier, TType};
use thrift::protocol::field_id;
use thrift::protocol::verify_expected_message_type;
use thrift::protocol::verify_expected_sequence_number;
use thrift::protocol::verify_expected_service_call;
use thrift::protocol::verify_required_field_exists;
use thrift::server::TProcessor;

//
// TQueryCacheParam
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct TQueryCacheParam {
  pub node_id: Option<i32>,
  pub digest: Option<Vec<u8>>,
  pub output_slot_mapping: Option<BTreeMap<i32, i32>>,
  pub tablet_to_range: Option<BTreeMap<i64, String>>,
  pub force_refresh_query_cache: Option<bool>,
  pub entry_max_bytes: Option<i64>,
  pub entry_max_rows: Option<i64>,
}

impl TQueryCacheParam {
  pub fn new<F1, F2, F3, F4, F5, F6, F7>(node_id: F1, digest: F2, output_slot_mapping: F3, tablet_to_range: F4, force_refresh_query_cache: F5, entry_max_bytes: F6, entry_max_rows: F7) -> TQueryCacheParam where F1: Into<Option<i32>>, F2: Into<Option<Vec<u8>>>, F3: Into<Option<BTreeMap<i32, i32>>>, F4: Into<Option<BTreeMap<i64, String>>>, F5: Into<Option<bool>>, F6: Into<Option<i64>>, F7: Into<Option<i64>> {
    TQueryCacheParam {
      node_id: node_id.into(),
      digest: digest.into(),
      output_slot_mapping: output_slot_mapping.into(),
      tablet_to_range: tablet_to_range.into(),
      force_refresh_query_cache: force_refresh_query_cache.into(),
      entry_max_bytes: entry_max_bytes.into(),
      entry_max_rows: entry_max_rows.into(),
    }
  }
}

impl TSerializable for TQueryCacheParam {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<TQueryCacheParam> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i32> = None;
    let mut f_2: Option<Vec<u8>> = None;
    let mut f_3: Option<BTreeMap<i32, i32>> = None;
    let mut f_4: Option<BTreeMap<i64, String>> = None;
    let mut f_5: Option<bool> = None;
    let mut f_6: Option<i64> = None;
    let mut f_7: Option<i64> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i32()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_bytes()?;
          f_2 = Some(val);
        },
        3 => {
          let map_ident = i_prot.read_map_begin()?;
          let mut val: BTreeMap<i32, i32> = BTreeMap::new();
          for _ in 0..map_ident.size {
            let map_key_0 = i_prot.read_i32()?;
            let map_val_1 = i_prot.read_i32()?;
            val.insert(map_key_0, map_val_1);
          }
          i_prot.read_map_end()?;
          f_3 = Some(val);
        },
        4 => {
          let map_ident = i_prot.read_map_begin()?;
          let mut val: BTreeMap<i64, String> = BTreeMap::new();
          for _ in 0..map_ident.size {
            let map_key_2 = i_prot.read_i64()?;
            let map_val_3 = i_prot.read_string()?;
            val.insert(map_key_2, map_val_3);
          }
          i_prot.read_map_end()?;
          f_4 = Some(val);
        },
        5 => {
          let val = i_prot.read_bool()?;
          f_5 = Some(val);
        },
        6 => {
          let val = i_prot.read_i64()?;
          f_6 = Some(val);
        },
        7 => {
          let val = i_prot.read_i64()?;
          f_7 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = TQueryCacheParam {
      node_id: f_1,
      digest: f_2,
      output_slot_mapping: f_3,
      tablet_to_range: f_4,
      force_refresh_query_cache: f_5,
      entry_max_bytes: f_6,
      entry_max_rows: f_7,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("TQueryCacheParam");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(fld_var) = self.node_id {
      o_prot.write_field_begin(&TFieldIdentifier::new("node_id", TType::I32, 1))?;
      o_prot.write_i32(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.digest {
      o_prot.write_field_begin(&TFieldIdentifier::new("digest", TType::String, 2))?;
      o_prot.write_bytes(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.output_slot_mapping {
      o_prot.write_field_begin(&TFieldIdentifier::new("output_slot_mapping", TType::Map, 3))?;
      o_prot.write_map_begin(&TMapIdentifier::new(TType::I32, TType::I32, fld_var.len() as i32))?;
      for (k, v) in fld_var {
        o_prot.write_i32(*k)?;
        o_prot.write_i32(*v)?;
      }
      o_prot.write_map_end()?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.tablet_to_range {
      o_prot.write_field_begin(&TFieldIdentifier::new("tablet_to_range", TType::Map, 4))?;
      o_prot.write_map_begin(&TMapIdentifier::new(TType::I64, TType::String, fld_var.len() as i32))?;
      for (k, v) in fld_var {
        o_prot.write_i64(*k)?;
        o_prot.write_string(v)?;
      }
      o_prot.write_map_end()?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.force_refresh_query_cache {
      o_prot.write_field_begin(&TFieldIdentifier::new("force_refresh_query_cache", TType::Bool, 5))?;
      o_prot.write_bool(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.entry_max_bytes {
      o_prot.write_field_begin(&TFieldIdentifier::new("entry_max_bytes", TType::I64, 6))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.entry_max_rows {
      o_prot.write_field_begin(&TFieldIdentifier::new("entry_max_rows", TType::I64, 7))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

